# Generated by Django 4.1.3 on 2022-12-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNew', '0002_paseo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mascota',
        ),
        migrations.DeleteModel(
            name='paseo',
        ),
    ]
